// <auto-generated />
using System;
using CamadaRepositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamadaRepositorio.Migrations
{
    [DbContext(typeof(ConProContexto))]
    partial class ConProContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CamadaModelo.Entidades.Apontamento", b =>
                {
                    b.Property<int>("CodigoApontamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_APONTAMENTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoApontamento"), 1L, 1);

                    b.Property<int>("COD_IMPLEMENTACAO")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INICIO");

                    b.Property<string>("DescricaoRealizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DES_REALIZADO");

                    b.Property<TimeSpan>("Tempo")
                        .HasColumnType("time")
                        .HasColumnName("TEMPO");

                    b.HasKey("CodigoApontamento");

                    b.HasIndex("COD_IMPLEMENTACAO");

                    b.ToTable("APONTAMENTO");
                });

            modelBuilder.Entity("CamadaModelo.Entidades.Implementacao", b =>
                {
                    b.Property<int>("CodigoImplementacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_PROJETO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoImplementacao"), 1L, 1);

                    b.Property<bool>("Cobrado")
                        .HasColumnType("bit")
                        .HasColumnName("COBRADO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DES_IMPLEMENTACAO");

                    b.Property<TimeSpan>("TempoTotal")
                        .HasColumnType("time")
                        .HasColumnName("TEMPO_TOTAL");

                    b.HasKey("CodigoImplementacao");

                    b.ToTable("IMPLEMENTACAO");
                });

            modelBuilder.Entity("CamadaModelo.Entidades.Apontamento", b =>
                {
                    b.HasOne("CamadaModelo.Entidades.Implementacao", "Implementacao")
                        .WithMany("Apontamentos")
                        .HasForeignKey("COD_IMPLEMENTACAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Implementacao");
                });

            modelBuilder.Entity("CamadaModelo.Entidades.Implementacao", b =>
                {
                    b.Navigation("Apontamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
